# This is a basic workflow to help you get started with Actions

name: Build test

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  release:
     types: [ released ] 
      

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
    - uses: octokit/request-action@v2.x
      id: get_latest_release
      with:
        route: GET /repos/:repository/releases/latest
        repository: ${{ github.repository }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Notify that deploy starts
      uses: appleboy/telegram-action@0.0.7
      with:
        token: ${{ secrets.TG_BOT_TOKEN }}        
        to: ${{ secrets.TG_CICD_CHANNEL_ID }}
        format: markdown
        message: |
          **FTB-ADMIN**
          Release `${{ steps.get_latest_release.outputs.data.tag_name }}` is building and shipping to production
    
    - name: Build
      run: echo "I'm building"
      
    - name: Build Failure
      if: ${{ failure() }}
      uses: appleboy/telegram-action@0.0.7
      with:
        token: ${{ secrets.TG_BOT_TOKEN }}        
        to: ${{ secrets.TG_CICD_CHANNEL_ID }}
        format: markdown
        message: |
          **FTB-ADMIN**
          ⚠️ Release `${{ steps.get_latest_release.outputs.data.tag_name }}` has failed at build state ⚠️
                
    - name: Deploy
      if: ${{ success() }}
      run: echo "I'm deploying"
      
    - name: Build
      run: echo "I'm building"
      
    - name: Deploy Failure
      if: ${{ failure() }}
      uses: appleboy/telegram-action@0.0.7
      with:
        token: ${{ secrets.TG_BOT_TOKEN }}        
        to: ${{ secrets.TG_CICD_CHANNEL_ID }}
        format: markdown
        message: |
          **FTB-ADMIN**
          ⚠️ Release `${{ steps.get_latest_release.outputs.data.tag_name }}` has failed at deploy state ⚠️
      
    - name: Deploy Success
      if: ${{ success() }}
      uses: appleboy/telegram-action@0.0.7
      with:
        token: ${{ secrets.TG_BOT_TOKEN }}        
        to: ${{ secrets.TG_CICD_CHANNEL_ID }}
        format: markdown
        message: |
          **FTB-ADMIN**
          ✅ Release`${{ steps.get_latest_release.outputs.data.tag_name }}` landed on production 🎉
          
      
